
name: Comic Strip Readme

on:
    
    schedule:
        # Runs at 5:30 am IST every Monday, Wednesday, Friday
        - cron: "0 0 * * 1,3,5"
    workflow_dispatch:

jobs:
    update-readme:
        name: Update README with Comic Strip
        runs-on: ubuntu-latest
        steps:
            - uses: ism0080/comicstrip-readme@v1.2
              with:
                  SHOW_XKCD: true
